/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as ApiIngestCheckRouteImport } from './routes/api/ingest/check'
import { Route as ApiIngestReceiveRouteImport } from './routes/api/ingest/receive'
import { Route as ApiPublicPreviewsSplatRouteImport } from './routes/api/public/previews.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestCheckRoute = ApiIngestCheckRouteImport.update({
  id: '/api/ingest/check',
  path: '/api/ingest/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestReceiveRoute = ApiIngestReceiveRouteImport.update({
  id: '/api/ingest/receive',
  path: '/api/ingest/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPreviewsSplatRoute = ApiPublicPreviewsSplatRouteImport.update({
  id: '/api/public/previews/$',
  path: '/api/public/previews/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/match/$id': typeof MatchIdRoute
  '/api/ingest/check': typeof ApiIngestCheckRoute
  '/api/ingest/receive': typeof ApiIngestReceiveRoute
  '/api/public/previews/$': typeof ApiPublicPreviewsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/match/$id': typeof MatchIdRoute
  '/api/ingest/check': typeof ApiIngestCheckRoute
  '/api/ingest/receive': typeof ApiIngestReceiveRoute
  '/api/public/previews/$': typeof ApiPublicPreviewsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/match/$id': typeof MatchIdRoute
  '/api/ingest/check': typeof ApiIngestCheckRoute
  '/api/ingest/receive': typeof ApiIngestReceiveRoute
  '/api/public/previews/$': typeof ApiPublicPreviewsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/match/$id'
    | '/api/ingest/check'
    | '/api/ingest/receive'
    | '/api/public/previews/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/match/$id'
    | '/api/ingest/check'
    | '/api/ingest/receive'
    | '/api/public/previews/$'
  id:
    | '__root__'
    | '/'
    | '/match/$id'
    | '/api/ingest/check'
    | '/api/ingest/receive'
    | '/api/public/previews/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchIdRoute: typeof MatchIdRoute
  ApiIngestCheckRoute: typeof ApiIngestCheckRoute
  ApiIngestReceiveRoute: typeof ApiIngestReceiveRoute
  ApiPublicPreviewsSplatRoute: typeof ApiPublicPreviewsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/check': {
      id: '/api/ingest/check'
      path: '/api/ingest/check'
      fullPath: '/api/ingest/check'
      preLoaderRoute: typeof ApiIngestCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/receive': {
      id: '/api/ingest/receive'
      path: '/api/ingest/receive'
      fullPath: '/api/ingest/receive'
      preLoaderRoute: typeof ApiIngestReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/previews/$': {
      id: '/api/public/previews/$'
      path: '/api/public/previews/$'
      fullPath: '/api/public/previews/$'
      preLoaderRoute: typeof ApiPublicPreviewsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchIdRoute: MatchIdRoute,
  ApiIngestCheckRoute: ApiIngestCheckRoute,
  ApiIngestReceiveRoute: ApiIngestReceiveRoute,
  ApiPublicPreviewsSplatRoute: ApiPublicPreviewsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
